apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stock-ticker
  name: stock-ticker
  namespace: forgerock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-ticker
  template:
    metadata:
      labels:
        app: stock-ticker
    spec:
      containers:
      - name: app
        env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: stock-ticker-config
              key: LOG_LEVEL
        - name: SYMBOL
          valueFrom:
            configMapKeyRef:
              name: stock-ticker-config
              key: SYMBOL
        - name: NDAYS
          valueFrom:
            configMapKeyRef:
              name: stock-ticker-config
              key: NDAYS
        - name: STOCKS_API_HOST
          valueFrom:
            configMapKeyRef:
              name: stock-ticker-config
              key: STOCKS_API_HOST
        - name: STOCKS_API_KEY
          valueFrom:
            secretKeyRef:
              name: stock-ticker-secrets
              key: apikey
        - name: ENABLE_METRICS
          valueFrom:
            configMapKeyRef:
              name: stock-ticker-config
              key: ENABLE_METRICS
        image: stock-ticker:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: default
          protocol: TCP
        resources: {}
